### ISSUE TITLE
Type normalization

### ISSUE THREAD

**Issue by shaneburns** [tightenco/overload#6]
Hey, I'm really enjoying this overload trait! However, in using it for a project, I have found that parameters of bool and float types do not behave as expected. I dug into the code a bit and found that, currently, only variables of type int are being normalized to their backwards compatible alias, 'integer'.  PHP's built-in gettype() function returns 'boolean' for variables of type bool and 'double' for variables of type float. Accounting for this in the normalizeTypes() method of the OverloadableMethodCandidate class does the trick.

Can I make a pull request to add these type normalizations and implement tests for them?
( p.s. this is the first issue I've ever done on github. I did read the contribution guidelines, however if I need change something I'm more than happy to do so)

**Comment by mattstauffer** [comment]
I would love that! Thanks so much @shaneburns and welcome to OSS contributions!!
